### ISSUE TITLE
Rnadom image generator

### ISSUE THREAD

**Issue by Trox7x** [stivbot/sandbox#15]
I'm trying to build a random image generator, can you help me ?

**Comment by LucBerge** [comment]
Hello @Trox7x, the bot server is not responding. My apologize for this issue, I'll fix it ASAP

**Comment by LucBerge** [comment]
@Trox7x The app has been restarted and is back to normal. Unfortunately, you will have to open a new issue to trigger a new bot conversation.

**Comment by Trox7x** [comment]
thnx, gonna retry

**Comment by LucBerge** [comment]
Issue opened : https://github.com/stivbot/stivbot/issues/19
